# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spec.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='spec.proto',
  package='TTSpecProtobuf',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nspec.proto\x12\x0eTTSpecProtobuf\"T\n\x08SongInfo\x12\x10\n\x08trackRef\x18\x01 \x01(\t\x12\x0e\n\x06songID\x18\x02 \x01(\x03\x12\x11\n\tgameSpeed\x18\x03 \x01(\x02\x12\x13\n\x0bscrollSpeed\x18\x04 \x01(\x02\"K\n\tFrameData\x12\x12\n\nnoteHolder\x18\x01 \x01(\x02\x12\x17\n\x0fpointerPosition\x18\x02 \x01(\x02\x12\x11\n\tisTooting\x18\x03 \x01(\x08\x62\x06proto3'
)




_SONGINFO = _descriptor.Descriptor(
  name='SongInfo',
  full_name='TTSpecProtobuf.SongInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='trackRef', full_name='TTSpecProtobuf.SongInfo.trackRef', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='songID', full_name='TTSpecProtobuf.SongInfo.songID', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gameSpeed', full_name='TTSpecProtobuf.SongInfo.gameSpeed', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='scrollSpeed', full_name='TTSpecProtobuf.SongInfo.scrollSpeed', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=114,
)


_FRAMEDATA = _descriptor.Descriptor(
  name='FrameData',
  full_name='TTSpecProtobuf.FrameData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='noteHolder', full_name='TTSpecProtobuf.FrameData.noteHolder', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pointerPosition', full_name='TTSpecProtobuf.FrameData.pointerPosition', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isTooting', full_name='TTSpecProtobuf.FrameData.isTooting', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=191,
)

DESCRIPTOR.message_types_by_name['SongInfo'] = _SONGINFO
DESCRIPTOR.message_types_by_name['FrameData'] = _FRAMEDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SongInfo = _reflection.GeneratedProtocolMessageType('SongInfo', (_message.Message,), {
  'DESCRIPTOR' : _SONGINFO,
  '__module__' : 'spec_pb2'
  # @@protoc_insertion_point(class_scope:TTSpecProtobuf.SongInfo)
  })
_sym_db.RegisterMessage(SongInfo)

FrameData = _reflection.GeneratedProtocolMessageType('FrameData', (_message.Message,), {
  'DESCRIPTOR' : _FRAMEDATA,
  '__module__' : 'spec_pb2'
  # @@protoc_insertion_point(class_scope:TTSpecProtobuf.FrameData)
  })
_sym_db.RegisterMessage(FrameData)


# @@protoc_insertion_point(module_scope)
